FROM registry.access.redhat.com/ubi9/nodejs-22:latest

# Install yarn globally (requires root)
USER root
RUN command -v yarn || npm i -g yarn

# Switch to default non-root user
USER 1001

WORKDIR /usr/src/app

COPY --chown=1001:0 package.json yarn.lock ./
RUN yarn install

COPY --chown=1001:0 . .

EXPOSE 9001

CMD ["yarn", "run", "start"]
